### PR TITLE
fix(Transition/shaders): remove circular dependency

### LINKED ISSUE #52: Warnings Emitted from Rollup When Building
When I rollup the project - the folliong circular dependencies are called out - 

```
(!) Circular dependency: node_modules/wpe-lightning/src/tree/Element.mjs -> node_modules/wpe-lightning/src/animation/Transition.mjs -> node_modules/wpe-lightning/src/tree/Element.mjs
(!) Circular dependency: node_modules/wpe-lightning/src/renderer/webgl/shaders/GrayscaleShader.mjs -> node_modules/wpe-lightning/src/renderer/c2d/shaders/GrayscaleShader.mjs -> node_modules/wpe-lightning/src/renderer/webgl/shaders/GrayscaleShader.mjs
```

Would it be possible to get these cleaned up?

### PR DESCRIPTION
**Pull request by erikhaandrikman**
Resolve #52

### CODE REVIEW

File: src/animation/Transition.mjs [hunk 1]
```diff
@@ -197,6 +204,9 @@ export default class Transition extends EventEmitter {
     }
 
 }
+Transition.getGetterProxy = null;
```
Comment (g-zachar) [inline src/animation/Transition.mjs]: What do we need those proxy methods for?

Comment (erikhaandrikman) [reply src/animation/Transition.mjs]: Well actually we don't need them, i've committed a change
